# Generated by Django 3.2.4 on 2021-07-05 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='signup_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('Address', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=100)),
                ('phone_no', models.CharField(default='', max_length=12)),
                ('collage_name', models.CharField(default='', max_length=100)),
                ('Branch', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('passwordre', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Extende_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
