# Generated by Django 3.2.4 on 2021-07-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_signup_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_user',
            name='image',
            field=models.ImageField(default='', upload_to='profile_img'),
        ),
    ]
