# Generated by Django 3.2.4 on 2021-07-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_signup_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_user',
            name='image',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
