# Generated by Django 3.2.6 on 2021-08-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_subscribed_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='subscribed_email',
        ),
    ]
